import type { RoutePayload } from 'twenty-sdk';

import { SAVE_WRITE_DRAFT_FUNCTION_UNIVERSAL_IDENTIFIER } from 'src/constants/universal-identifiers';
import { defineLogicFunction } from 'src/utils/define-logic-function';
import { handleSaveWriteDraftRoute } from 'src/utils/codex-tools';

const handler = async (
  event: RoutePayload<Record<string, unknown> | string | null>,
): Promise<Record<string, unknown>> => handleSaveWriteDraftRoute(event);

export default defineLogicFunction({
  universalIdentifier: SAVE_WRITE_DRAFT_FUNCTION_UNIVERSAL_IDENTIFIER,
  name: 'save-write-draft',
  description: 'Stores a write draft generated by the Codex runner',
  timeoutSeconds: 10,
  handler,
  httpRouteTriggerSettings: {
    path: '/tools/save-write-draft',
    httpMethod: 'POST',
    isAuthRequired: false,
    forwardedRequestHeaders: ['x-tool-shared-secret', 'content-type'],
  },
});
